package com.samjaygill.Samify.components;

import com.samjaygill.Samify.models.Album;
import com.samjaygill.Samify.models.Artist;
import com.samjaygill.Samify.models.Song;
import com.samjaygill.Samify.repository.AlbumRepository;
import com.samjaygill.Samify.repository.ArtistRepository;
import com.samjaygill.Samify.repository.SongRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Profile("!test") //Run every time EXCEPT Tests
@Component
public class DataLoader implements ApplicationRunner {

    @Autowired
    ArtistRepository artistRepository;

    @Autowired
    AlbumRepository albumRepository;

    @Autowired
    SongRepository songRepository;


    public DataLoader() {
    }

    public void run(ApplicationArguments args) {


        Artist eminem = new Artist("Eminem", "Marshall Mathers", "https://i.ibb.co/kyNgCDs/eminem-removebg-preview.png", 51, "17/10/1972", "Detroit", "Bio of Eminem");
        Artist fiftyCent = new Artist("50 Cent", "Curtis James Jackson III", "https://i.ibb.co/6rg2y9t/50cent-removebg-preview.png", 48, "06/07/1975", "New York", "Bio of 50 cent");
        Artist chrisBrown = new Artist("Chris Brown", "Christopher Maurice Brown", "https://i.ibb.co/zF8Jwy8/cb-removebg-preview.png", 34, "05/05/1989", "Virginia", "Bio of Chris Brown");
        Artist beyonce = new Artist("Beyoncé", "Beyoncé Giselle Knowles-Carter", "https://i.ibb.co/ZYz4CKR/bey-removebg-preview.png", 42, "04/09/1981", "Houston", "Bio of Beyonce");
        Artist rihanna = new Artist("Rihanna", "Robyn Rihanna Fenty", "https://i.ibb.co/JBVkNsY/rih-removebg-preview.png", 36, "20/02/1988", "Barbados", "Bio of Rihanna");
        Artist vybz = new Artist("Vybz Kartel", "Adidja Azim Palmer", "https://i.ibb.co/L0HsnHZ/vk-removebg-preview.png", 48, "07/01/1976", "Jamaica", "Bio of Vybz Kartel");
        Artist dre = new Artist("Dr. Dre", "Andre Romell Young", "https://i.ibb.co/1Gw86Lk/dre-removebg-preview.png", 59, "18/02/1965", "Compton", "Bio of Dr. Dre");
        Artist drake = new Artist("Drake", "Aubrey Drake Graham", "https://i.ibb.co/tQSL6N5/drake-removebg-preview.png", 37, "24/10/1986", "Toronto", "Bio of Drake");

        artistRepository.saveAll(Arrays.asList(eminem, fiftyCent, chrisBrown, beyonce, rihanna, vybz, dre, drake));


        Album mmlp = new Album("The Marshall Mathers LP", "https://i1.sndcdn.com/artworks-46d4a422-15df-4966-a771-33fdbca3922f-0-t500x500.jpg", "23/05/2000", "Hip-Hop", 5);
        Album sslp = new Album("The Slim Shady LP", "https://upload.wikimedia.org/wikipedia/en/3/35/Eminem_-_The_Slim_Shady_LP_CD_cover.jpg", "23/02/1999", "Hip-Hop", 4);
        Album tes = new Album("The Eminem Show", "https://upload.wikimedia.org/wikipedia/en/3/35/The_Eminem_Show.jpg", "26/05/2002", "Hip-Hop", 5);
        Album encore = new Album("Encore", "https://upload.wikimedia.org/wikipedia/en/b/b4/Encore_%28Eminem_album%29_coverart.jpg", "12/11/2004", "Hip-Hop", 4);
        Album recovery = new Album("Recovery", "https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg", "18/06/2010", "Hip-Hop", 5);
        Album mmlptwo = new Album("The Marshall Mathers LP 2", "https://upload.wikimedia.org/wikipedia/en/8/87/The_Marshall_Mathers_LP_2.png", "05/11/2013", "Hip-Hop", 5);

        mmlp.setArtist(eminem);
        sslp.setArtist(eminem);
        tes.setArtist(eminem);
        encore.setArtist(eminem);
        recovery.setArtist(eminem);
        mmlptwo.setArtist(eminem);

        eminem.getAlbums().addAll(Arrays.asList(mmlp, sslp, tes, encore, recovery, mmlptwo));

        List<Song> mmlpSongs = new ArrayList<>();
        mmlpSongs.add(new Song("Public Service Announcement 2000"));
        mmlpSongs.add(new Song("Kill You"));
        mmlpSongs.add(new Song("Stan"));
        mmlpSongs.add(new Song("Paul (skit)"));
        mmlpSongs.add(new Song("Who Knew"));
        mmlpSongs.add(new Song("Steve Berman (skit)"));
        mmlpSongs.add(new Song("The Way I Am"));
        mmlpSongs.add(new Song("The Real Slim Shady"));
        mmlpSongs.add(new Song("Remember Me?"));
        mmlpSongs.add(new Song("I'm Back"));
        mmlpSongs.add(new Song("Marshall Mathers"));
        mmlpSongs.add(new Song("Ken Kaniff (skit)"));
        mmlpSongs.add(new Song("Drug Ballad"));
        mmlpSongs.add(new Song("Amityville"));
        mmlpSongs.add(new Song("Bitch Please II"));
        mmlpSongs.add(new Song("Kim"));
        mmlpSongs.add(new Song("Under the Influence"));
        mmlpSongs.add(new Song("Criminal"));
        mmlpSongs.forEach(mmlp::addSong);

        List<Song> sslpSongs = new ArrayList<>();
        sslpSongs.add(new Song("Public Service Announcement"));
        sslpSongs.add(new Song("My Name Is"));
        sslpSongs.add(new Song("Guilty Conscience"));
        sslpSongs.add(new Song("Brain Damage"));
        sslpSongs.add(new Song("Paul (skit)"));
        sslpSongs.add(new Song("If I Had"));
        sslpSongs.add(new Song("'97 Bonnie & Clyde"));
        sslpSongs.add(new Song("Bitch (skit)"));
        sslpSongs.add(new Song("Role Model"));
        sslpSongs.add(new Song("Lounge (skit)"));
        sslpSongs.add(new Song("My Fault"));
        sslpSongs.add(new Song("Ken Kaniff (skit)"));
        sslpSongs.add(new Song("Cum on Everybody"));
        sslpSongs.add(new Song("Rock Bottom"));
        sslpSongs.add(new Song("Just Don't Give a Fuck"));
        sslpSongs.add(new Song("Soap (skit)"));
        sslpSongs.add(new Song("As the World Turns"));
        sslpSongs.add(new Song("I'm Shady"));
        sslpSongs.add(new Song("Bad Meets Evil"));
        sslpSongs.add(new Song("Still Don't Give a Fuck"));
        sslpSongs.forEach(sslp::addSong);

        List<Song> tesSongs = new ArrayList<>();
        tesSongs.add(new Song("Curtains Up (Skit)"));
        tesSongs.add(new Song("White America"));
        tesSongs.add(new Song("Business"));
        tesSongs.add(new Song("Cleanin' Out My Closet"));
        tesSongs.add(new Song("Square Dance"));
        tesSongs.add(new Song("The Kiss (Skit)"));
        tesSongs.add(new Song("Soldier"));
        tesSongs.add(new Song("Say Goodbye Hollywood"));
        tesSongs.add(new Song("Drips"));
        tesSongs.add(new Song("Without Me"));
        tesSongs.add(new Song("Paul Rosenberg (Skit)"));
        tesSongs.add(new Song("Sing for the Moment"));
        tesSongs.add(new Song("Superman"));
        tesSongs.add(new Song("Hailie's Song"));
        tesSongs.add(new Song("Steve Berman (Skit)"));
        tesSongs.add(new Song("When the Music Stops"));
        tesSongs.add(new Song("Say What You Say"));
        tesSongs.add(new Song("'Till I Collapse"));
        tesSongs.add(new Song("My Dad's Gone Crazy"));
        tesSongs.add(new Song("Curtains Close (Skit)"));
        tesSongs.forEach(tes::addSong);

        List<Song> encoreSongs = new ArrayList<>();
        encoreSongs.add(new Song("Curtains Up (skit)"));
        encoreSongs.add(new Song("Evil Deeds"));
        encoreSongs.add(new Song("Never Enough"));
        encoreSongs.add(new Song("Yellow Brick Road"));
        encoreSongs.add(new Song("Like Toy Soldiers"));
        encoreSongs.add(new Song("Mosh"));
        encoreSongs.add(new Song("Puke"));
        encoreSongs.add(new Song("My 1st Single"));
        encoreSongs.add(new Song("Paul (skit)"));
        encoreSongs.add(new Song("Rain Man"));
        encoreSongs.add(new Song("Big Weenie"));
        encoreSongs.add(new Song("Em Calls Paul (skit)"));
        encoreSongs.add(new Song("Just Lose It"));
        encoreSongs.add(new Song("Ass Like That"));
        encoreSongs.add(new Song("Spend Some Time"));
        encoreSongs.add(new Song("Mockingbird"));
        encoreSongs.add(new Song("Crazy in Love"));
        encoreSongs.add(new Song("One Shot 2 Shot"));
        encoreSongs.add(new Song("Final Thought (skit)"));
        encoreSongs.add(new Song("Encore / Curtains Down"));
        encoreSongs.forEach(encore::addSong);

        List<Song> recoverySongs = new ArrayList<>();
        recoverySongs.add(new Song("Cold Wind Blows"));
        recoverySongs.add(new Song("Talkin' 2 Myself"));
        recoverySongs.add(new Song("On Fire"));
        recoverySongs.add(new Song("Won't Back Down"));
        recoverySongs.add(new Song("W.T.P"));
        recoverySongs.add(new Song("Going Through Changes"));
        recoverySongs.add(new Song("Not Afraid"));
        recoverySongs.add(new Song("Seduction"));
        recoverySongs.add(new Song("No Love"));
        recoverySongs.add(new Song("Space Bound"));
        recoverySongs.add(new Song("Cinderella Man"));
        recoverySongs.add(new Song("25 to Life"));
        recoverySongs.add(new Song("So Bad"));
        recoverySongs.add(new Song("Almost Famous"));
        recoverySongs.add(new Song("Love the Way You Lie"));
        recoverySongs.add(new Song("You're Never Over"));
        recoverySongs.add(new Song("Untitled"));
        recoverySongs.forEach(recovery::addSong);

        List<Song> mmlptwoSongs = new ArrayList<>();
        mmlptwoSongs.add(new Song("Bad Guy"));
        mmlptwoSongs.add(new Song("Parking Lot (Skit)"));
        mmlptwoSongs.add(new Song("Rhyme or Reason"));
        mmlptwoSongs.add(new Song("So Much Better"));
        mmlptwoSongs.add(new Song("Survival"));
        mmlptwoSongs.add(new Song("Legacy"));
        mmlptwoSongs.add(new Song("Asshole"));
        mmlptwoSongs.add(new Song("Berzerk"));
        mmlptwoSongs.add(new Song("Rap God"));
        mmlptwoSongs.add(new Song("Brainless"));
        mmlptwoSongs.add(new Song("Stronger Than I Was"));
        mmlptwoSongs.add(new Song("The Monster"));
        mmlptwoSongs.add(new Song("So Far..."));
        mmlptwoSongs.add(new Song("Love Game"));
        mmlptwoSongs.add(new Song("Headlights"));
        mmlptwoSongs.add(new Song("Evil Twin"));
        mmlptwoSongs.forEach(mmlptwo::addSong);

        Album grodt = new Album("Get Rich or Die Tryin'", "https://upload.wikimedia.org/wikipedia/en/9/9d/Get_Rich_Or_Die_Tryin%27.JPG", "06/02/2003", "Hip-Hop", 4);
        grodt.setArtist(fiftyCent);
        fiftyCent.getAlbums().add(grodt);

        List<Song> grodtSongs = new ArrayList<>();
        grodtSongs.add(new Song("Intro"));
        grodtSongs.add(new Song("What Up Gangsta"));
        grodtSongs.add(new Song("Patiently Waiting"));
        grodtSongs.add(new Song("Many Men (Wish Death)"));
        grodtSongs.add(new Song("In da Club"));
        grodtSongs.add(new Song("High All the Time"));
        grodtSongs.add(new Song("Heat"));
        grodtSongs.add(new Song("If I Can't"));
        grodtSongs.add(new Song("Blood Hound"));
        grodtSongs.add(new Song("Back Down"));
        grodtSongs.add(new Song("P.I.M.P."));
        grodtSongs.add(new Song("Like My Style"));
        grodtSongs.add(new Song("Poor Lil Rich"));
        grodtSongs.add(new Song("21 Questions"));
        grodtSongs.add(new Song("Don't Push Me"));
        grodtSongs.add(new Song("Gotta Make It to Heaven"));
        grodtSongs.add(new Song("Wanksta"));
        grodtSongs.add(new Song("U Not Like Me"));
        grodtSongs.add(new Song("Life's on the Line"));
        grodtSongs.forEach(grodt::addSong);

        Album cb = new Album("Chris Brown", "https://upload.wikimedia.org/wikipedia/en/c/ce/Chris_brown.jpg", "25/11/2005", "R&B", 4);
        Album fame = new Album("F.A.M.E.", "https://upload.wikimedia.org/wikipedia/en/d/d6/ForgivingAllMyEnemies.PNG", "18/03/2011", "R&B", 3);
        Album royalty = new Album("Royalty", "https://upload.wikimedia.org/wikipedia/en/a/a4/Royalty_Chris_Brown.jpg", "18/12/2015", "R&B", 4);
        Album hoafm = new Album("Heartbreak on a Full Moon", "https://upload.wikimedia.org/wikipedia/en/e/ee/Chris_Brown_-_Heartbreak_on_a_Full_Moon.png", "31/10/2017", "R&B", 5);
        Album breezy = new Album("Breezy", "https://upload.wikimedia.org/wikipedia/en/3/33/Chris_Brown_-_Breezy.png", "24/06/2022", "R&B", 4);
        Album eleven = new Album("11:11", "https://upload.wikimedia.org/wikipedia/en/c/c7/Chris_Brown_-_11-11_Cover.jpeg", "10/11/2023", "R&B", 5);
        cb.setArtist(chrisBrown);
        fame.setArtist(chrisBrown);
        royalty.setArtist(chrisBrown);
        hoafm.setArtist(chrisBrown);
        breezy.setArtist(chrisBrown);
        eleven.setArtist(chrisBrown);
        chrisBrown.getAlbums().addAll(Arrays.asList(cb, fame, royalty, hoafm, breezy, eleven));

        List<Song> cbSongs = new ArrayList<>();
        cbSongs.add(new Song("Intro"));
        cbSongs.add(new Song("Run It!"));
        cbSongs.add(new Song("Yo (Excuse Me Miss)"));
        cbSongs.add(new Song("Young Love"));
        cbSongs.add(new Song("Gimme That"));
        cbSongs.add(new Song("Ya Man Ain't Me"));
        cbSongs.add(new Song("Winner"));
        cbSongs.add(new Song("Ain't No Way (You Won't Love Me)"));
        cbSongs.add(new Song("What's My Name"));
        cbSongs.add(new Song("Is This Love?"));
        cbSongs.add(new Song("Poppin'"));
        cbSongs.add(new Song("Just Fine"));
        cbSongs.add(new Song("Say Goodbye"));
        cbSongs.add(new Song("Run It! (Remix)"));
        cbSongs.add(new Song("Thank You"));
        cbSongs.add(new Song("Gimme That (Remix)"));
        cbSongs.forEach(cb::addSong);

        List<Song> fameSongs = new ArrayList<>();
        fameSongs.add(new Song("Deuces"));
        fameSongs.add(new Song("Up to You"));
        fameSongs.add(new Song("No Bullshit"));
        fameSongs.add(new Song("Look at Me Now"));
        fameSongs.add(new Song("She Ain't You"));
        fameSongs.add(new Song("Say It with Me"));
        fameSongs.add(new Song("Yeah 3x"));
        fameSongs.add(new Song("Next to You"));
        fameSongs.add(new Song("All Back"));
        fameSongs.add(new Song("Wet the Bed"));
        fameSongs.add(new Song("Oh My Love"));
        fameSongs.add(new Song("Should've Kissed You"));
        fameSongs.add(new Song("Beautiful People"));
        fameSongs.add(new Song("Champion"));
        fameSongs.forEach(fame::addSong);

        List<Song> royaltySongs = new ArrayList<>();
        royaltySongs.add(new Song("Back to Sleep"));
        royaltySongs.add(new Song("Fine by Me"));
        royaltySongs.add(new Song("Wrist"));
        royaltySongs.add(new Song("Make Love"));
        royaltySongs.add(new Song("Liquor"));
        royaltySongs.add(new Song("Zero"));
        royaltySongs.add(new Song("Anyway"));
        royaltySongs.add(new Song("Picture Me Rollin'"));
        royaltySongs.add(new Song("Who's Gonna (Nobody)"));
        royaltySongs.add(new Song("Discover"));
        royaltySongs.add(new Song("Little Bit"));
        royaltySongs.add(new Song("Proof"));
        royaltySongs.add(new Song("No Filter"));
        royaltySongs.add(new Song("Little More (Royalty)"));
        royaltySongs.forEach(royalty::addSong);

        List<Song> hoafmSongs = new ArrayList<>();
        hoafmSongs.add(new Song("Lost & Found"));
        hoafmSongs.add(new Song("Privacy"));
        hoafmSongs.add(new Song("Juicy Booty"));
        hoafmSongs.add(new Song("Questions"));
        hoafmSongs.add(new Song("Heartbreak on a Full Moon"));
        hoafmSongs.add(new Song("Roses"));
        hoafmSongs.add(new Song("Confidence"));
        hoafmSongs.add(new Song("Rock Your Body"));
        hoafmSongs.add(new Song("Tempo"));
        hoafmSongs.add(new Song("Handle It"));
        hoafmSongs.add(new Song("Sip"));
        hoafmSongs.add(new Song("Everybody Knows"));
        hoafmSongs.add(new Song("To My Bed"));
        hoafmSongs.add(new Song("Hope You Do"));
        hoafmSongs.add(new Song("This Ain't"));
        hoafmSongs.add(new Song("Pull Up"));
        hoafmSongs.add(new Song("Party"));
        hoafmSongs.add(new Song("Sensei"));
        hoafmSongs.add(new Song("Summer Breeze"));
        hoafmSongs.add(new Song("No Exit"));
        hoafmSongs.add(new Song("Pills & Automobiles"));
        hoafmSongs.add(new Song("Hurt the Same"));
        hoafmSongs.add(new Song("I Love Her"));
        hoafmSongs.add(new Song("You Like"));
        hoafmSongs.add(new Song("Nowhere"));
        hoafmSongs.add(new Song("Other Niggas"));
        hoafmSongs.add(new Song("Tough Love"));
        hoafmSongs.add(new Song("Paradise"));
        hoafmSongs.add(new Song("Covered in You"));
        hoafmSongs.add(new Song("Even"));
        hoafmSongs.add(new Song("High End"));
        hoafmSongs.add(new Song("On Me"));
        hoafmSongs.add(new Song("Tell Me What to Do"));
        hoafmSongs.add(new Song("Frustrated"));
        hoafmSongs.add(new Song("Enemy"));
        hoafmSongs.add(new Song("If You're Down"));
        hoafmSongs.add(new Song("Bite My Tongue"));
        hoafmSongs.add(new Song("Run Away"));
        hoafmSongs.add(new Song("This Way"));
        hoafmSongs.add(new Song("Yellow Tape"));
        hoafmSongs.forEach(hoafm::addSong);

        List<Song> breezySongs = new ArrayList<>();
        breezySongs.add(new Song("Till the Wheels Fall Off"));
        breezySongs.add(new Song("C.A.B. (Catch a Body)"));
        breezySongs.add(new Song("Pitch Black"));
        breezySongs.add(new Song("Possessive"));
        breezySongs.add(new Song("Addicted"));
        breezySongs.add(new Song("Call Me Every Day"));
        breezySongs.add(new Song("Closure"));
        breezySongs.add(new Song("Need You Right Here"));
        breezySongs.add(new Song("Sex Memories"));
        breezySongs.add(new Song("Hmhmm"));
        breezySongs.add(new Song("Psychic"));
        breezySongs.add(new Song("Show It"));
        breezySongs.add(new Song("Sleep at Night"));
        breezySongs.add(new Song("Passing Time"));
        breezySongs.add(new Song("WE (Warm Embrace)"));
        breezySongs.add(new Song("Forbidden"));
        breezySongs.add(new Song("Bad Then a Beach"));
        breezySongs.add(new Song("Survive the Night"));
        breezySongs.add(new Song("Dream"));
        breezySongs.add(new Song("Slide"));
        breezySongs.add(new Song("Harder"));
        breezySongs.add(new Song("On Some New Shit"));
        breezySongs.add(new Song("Luckiest Man"));
        breezySongs.add(new Song("Iffy"));
        breezySongs.forEach(breezy::addSong);

        List<Song> elevenSongs = new ArrayList<>();
        elevenSongs.add(new Song("Angel Numbers / Ten Toes"));
        elevenSongs.add(new Song("Sensational"));
        elevenSongs.add(new Song("Press Me"));
        elevenSongs.add(new Song("That's On You"));
        elevenSongs.add(new Song("Feel Something"));
        elevenSongs.add(new Song("Best Ever"));
        elevenSongs.add(new Song("No One Else"));
        elevenSongs.add(new Song("Shooter"));
        elevenSongs.add(new Song("Nightmares"));
        elevenSongs.add(new Song("Very Special"));
        elevenSongs.add(new Song("Messed Up"));
        elevenSongs.add(new Song("Midnight Freak"));
        elevenSongs.add(new Song("Moonlight"));
        elevenSongs.add(new Song("Bouncing / G5"));
        elevenSongs.add(new Song("Make Up Your Mind"));
        elevenSongs.add(new Song("Stutter"));
        elevenSongs.add(new Song("Need a Friend"));
        elevenSongs.add(new Song("Summer Too Hot"));
        elevenSongs.add(new Song("Feelings Don't Lie"));
        elevenSongs.add(new Song("Red Flags"));
        elevenSongs.add(new Song("Closer"));
        elevenSongs.add(new Song("Views"));
        elevenSongs.forEach(eleven::addSong);

        Album iam = new Album("I Am... Sasha Fierce", "https://upload.wikimedia.org/wikipedia/en/9/96/I_Am..._Sasha_Fierce.png", "12/11/2008", "R&B", 4);
        Album four = new Album("4", "https://upload.wikimedia.org/wikipedia/en/c/ca/Beyonc%C3%A9_-_4.png", "24/06/2011", "R&B", 3);
        Album bey = new Album("Beyoncé", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Beyonc%C3%A9_-_Beyonc%C3%A9.svg/440px-Beyonc%C3%A9_-_Beyonc%C3%A9.svg.png", "13/12/2013", "R&B", 5);
        Album renais = new Album("Renaissance", "https://upload.wikimedia.org/wikipedia/en/a/ad/Beyonc%C3%A9_-_Renaissance.png", "29/07/2022", "Dance", 4);
        iam.setArtist(beyonce);
        four.setArtist(beyonce);
        bey.setArtist(beyonce);
        renais.setArtist(beyonce);
        beyonce.getAlbums().addAll(Arrays.asList(iam, four, bey, renais));

        List<Song> iamSongs = new ArrayList<>();
        iamSongs.add(new Song("Single Ladies (Put a Ring on It)"));
        iamSongs.add(new Song("Diva"));
        iamSongs.add(new Song("Ego"));
        iamSongs.add(new Song("Halo"));
        iamSongs.add(new Song("If I Were a Boy"));
        iamSongs.add(new Song("Smash Into You"));
        iamSongs.add(new Song("Sweet Dreams"));
        iamSongs.add(new Song("Broken-Hearted Girl"));
        iamSongs.add(new Song("Scared of Lonely"));
        iamSongs.add(new Song("That's Why You're Beautiful"));
        iamSongs.add(new Song("Hello"));
        iamSongs.add(new Song("Radio"));
        iamSongs.add(new Song("Video Phone"));
        iamSongs.add(new Song("Why Don't You Love Me"));
        iamSongs.add(new Song("Honesty"));
        iamSongs.add(new Song("Save the Hero"));
        iamSongs.add(new Song("Satellites"));
        iamSongs.add(new Song("Disappear"));
        iamSongs.add(new Song("Ave Maria"));
        iamSongs.forEach(iam::addSong);

        List<Song> fourSongs = new ArrayList<>();
        fourSongs.add(new Song("Love On Top"));
        fourSongs.add(new Song("Party"));
        fourSongs.add(new Song("Schoolin' Life"));
        fourSongs.add(new Song("Countdown"));
        fourSongs.add(new Song("I Miss You"));
        fourSongs.add(new Song("Dance for You"));
        fourSongs.add(new Song("I Care"));
        fourSongs.add(new Song("Rather Die Young"));
        fourSongs.add(new Song("1+1"));
        fourSongs.add(new Song("End of Time"));
        fourSongs.add(new Song("Run the World (Girls)"));
        fourSongs.add(new Song("Best Thing I Never Had"));
        fourSongs.add(new Song("Start Over"));
        fourSongs.add(new Song("I Was Here"));
        fourSongs.forEach(four::addSong);

        List<Song> beySongs = new ArrayList<>();
        beySongs.add(new Song("Pretty Hurts"));
        beySongs.add(new Song("Haunted"));
        beySongs.add(new Song("Drunk in Love"));
        beySongs.add(new Song("Blow"));
        beySongs.add(new Song("No Angel"));
        beySongs.add(new Song("Partition"));
        beySongs.add(new Song("Jealous"));
        beySongs.add(new Song("Rocket"));
        beySongs.add(new Song("Mine"));
        beySongs.add(new Song("XO"));
        beySongs.add(new Song("Flawless"));
        beySongs.add(new Song("Superpower"));
        beySongs.add(new Song("Heaven"));
        beySongs.add(new Song("Blue"));
        beySongs.add(new Song("Grown Woman"));
        beySongs.forEach(bey::addSong);

        List<Song> renaisSongs = new ArrayList<>();
        renaisSongs.add(new Song("I'm That Girl"));
        renaisSongs.add(new Song("Cozy"));
        renaisSongs.add(new Song("Alien Superstar"));
        renaisSongs.add(new Song("Cuff It"));
        renaisSongs.add(new Song("Energy"));
        renaisSongs.add(new Song("Break My Soul"));
        renaisSongs.add(new Song("Church Girl"));
        renaisSongs.add(new Song("Plastic Off the Sofa"));
        renaisSongs.add(new Song("Virgo's Groove"));
        renaisSongs.add(new Song("Move"));
        renaisSongs.add(new Song("Heated"));
        renaisSongs.add(new Song("Thique"));
        renaisSongs.add(new Song("All Up in Your Mind"));
        renaisSongs.add(new Song("America Has a Problem"));
        renaisSongs.add(new Song("Pure/Honey"));
        renaisSongs.add(new Song("Summer Renaissance"));
        renaisSongs.forEach(renais::addSong);

        Album gggb = new Album("Good Girl Gone Bad", "https://upload.wikimedia.org/wikipedia/en/f/f7/Good_Girl_Gone_Bad.png", "31/05/2007", "Pop", 4);
        Album loud = new Album("Loud", "https://upload.wikimedia.org/wikipedia/en/d/d1/Rihanna_-_Loud.png", "12/12/2010", "Pop", 5);
        Album ttt = new Album("Talk That Talk", "https://upload.wikimedia.org/wikipedia/en/8/8e/Rihanna_-_Talk_That_Talk_%28standard%29.png", "18/11/2011", "Pop", 4);
        Album unapologetic = new Album("Unapologetic", "https://upload.wikimedia.org/wikipedia/en/9/9b/Unapologetic_-_Rihanna.png", "19/11/2012", "Pop", 4);
        Album anti = new Album("Anti", "https://upload.wikimedia.org/wikipedia/en/3/32/Rihanna_-_Anti.png", "26/01/2016", "Pop", 3);
        gggb.setArtist(rihanna);
        loud.setArtist(rihanna);
        ttt.setArtist(rihanna);
        unapologetic.setArtist(rihanna);
        anti.setArtist(rihanna);
        rihanna.getAlbums().addAll(Arrays.asList(gggb, loud, ttt, unapologetic, anti));

        List<Song> gggbSongs = new ArrayList<>();
        gggbSongs.add(new Song("Umbrella"));
        gggbSongs.add(new Song("Push Up on Me"));
        gggbSongs.add(new Song("Don't Stop the Music"));
        gggbSongs.add(new Song("Breakin' Dishes"));
        gggbSongs.add(new Song("Shut Up and Drive"));
        gggbSongs.add(new Song("Hate That I Love You"));
        gggbSongs.add(new Song("Say It"));
        gggbSongs.add(new Song("Sell Me Candy"));
        gggbSongs.add(new Song("Lemme Get That"));
        gggbSongs.add(new Song("Rehab"));
        gggbSongs.add(new Song("Question Existing"));
        gggbSongs.add(new Song("Good Girl Gone Bad"));
        gggbSongs.forEach(gggb::addSong);

        List<Song> loudSongs = new ArrayList<>();
        loudSongs.add(new Song("S&M"));
        loudSongs.add(new Song("What's My Name?"));
        loudSongs.add(new Song("Cheers (Drink to That)"));
        loudSongs.add(new Song("Fading"));
        loudSongs.add(new Song("Only Girl (In the World)"));
        loudSongs.add(new Song("California King Bed"));
        loudSongs.add(new Song("Man Down"));
        loudSongs.add(new Song("Raining Men"));
        loudSongs.add(new Song("Complicated"));
        loudSongs.add(new Song("Skin"));
        loudSongs.add(new Song("Love the Way You Lie (Part II)"));
        loudSongs.forEach(loud::addSong);

        List<Song> tttSongs = new ArrayList<>();
        tttSongs.add(new Song("You da One"));
        tttSongs.add(new Song("Where Have You Been"));
        tttSongs.add(new Song("We Found Love"));
        tttSongs.add(new Song("Talk That Talk"));
        tttSongs.add(new Song("Cockiness (Love It)"));
        tttSongs.add(new Song("Birthday Cake"));
        tttSongs.add(new Song("We All Want Love"));
        tttSongs.add(new Song("Drunk on Love"));
        tttSongs.add(new Song("Roc Me Out"));
        tttSongs.add(new Song("Watch n' Learn"));
        tttSongs.add(new Song("Farewell"));
        tttSongs.add(new Song("Red Lipstick"));
        tttSongs.add(new Song("Do Ya Thang"));
        tttSongs.add(new Song("Fool in Love"));
        tttSongs.forEach(ttt::addSong);

        List<Song> unapologeticSongs = new ArrayList<>();
        unapologeticSongs.add(new Song("Phresh Out the Runway"));
        unapologeticSongs.add(new Song("Diamonds"));
        unapologeticSongs.add(new Song("Numb"));
        unapologeticSongs.add(new Song("Pour It Up"));
        unapologeticSongs.add(new Song("Loveeeeeee Song"));
        unapologeticSongs.add(new Song("Jump"));
        unapologeticSongs.add(new Song("Right Now"));
        unapologeticSongs.add(new Song("What Now"));
        unapologeticSongs.add(new Song("Stay"));
        unapologeticSongs.add(new Song("Nobody's Business"));
        unapologeticSongs.add(new Song("Love Without Tragedy / Mother Mary"));
        unapologeticSongs.add(new Song("Get It Over With"));
        unapologeticSongs.add(new Song("No Love Allowed"));
        unapologeticSongs.add(new Song("Lost in Paradise"));
        unapologeticSongs.add(new Song("Half of Me"));
        unapologeticSongs.forEach(unapologetic::addSong);

        List<Song> antiSongs = new ArrayList<>();
        antiSongs.add(new Song("Consideration"));
        antiSongs.add(new Song("James Joint"));
        antiSongs.add(new Song("Kiss It Better"));
        antiSongs.add(new Song("Work"));
        antiSongs.add(new Song("Desperado"));
        antiSongs.add(new Song("Woo"));
        antiSongs.add(new Song("Needed Me"));
        antiSongs.add(new Song("Yeah, I Said It"));
        antiSongs.add(new Song("Same Ol' Mistakes"));
        antiSongs.add(new Song("Never Ending"));
        antiSongs.add(new Song("Love on the Brain"));
        antiSongs.add(new Song("Higher"));
        antiSongs.add(new Song("Close to You"));
        antiSongs.add(new Song("Goodnight Gotham"));
        antiSongs.add(new Song("Pose"));
        antiSongs.add(new Song("S With Me"));
        antiSongs.add(new Song("Consideration"));
        antiSongs.add(new Song("Consideration"));
        antiSongs.add(new Song("Consideration"));
        antiSongs.forEach(anti::addSong);

        Album kingston = new Album("Kingston Story", "https://i.ibb.co/xfv8xD9/vkks.jpg", "21/06/2011", "Reggae", 5);
        Album kotd = new Album("King Of The Dancehall", "https://i.ibb.co/hgX5yMY/kodh.jpg", "10/06/2016", "Reggae", 3);
        kingston.setArtist(vybz);
        kotd.setArtist(vybz);
        vybz.getAlbums().addAll(Arrays.asList(kingston, kotd));

        List<Song> kingstonSongs = new ArrayList<>();
        kingstonSongs.add(new Song("Jamaica"));
        kingstonSongs.add(new Song("Beautiful Girl"));
        kingstonSongs.add(new Song("Half On A Baby"));
        kingstonSongs.add(new Song("Go Go Wine"));
        kingstonSongs.add(new Song("Yuh Love"));
        kingstonSongs.add(new Song("My Crew"));
        kingstonSongs.add(new Song("Breathless"));
        kingstonSongs.add(new Song("Mi Remember"));
        kingstonSongs.add(new Song("Push It In (Take It Out)"));
        kingstonSongs.add(new Song("Wine Pon Me"));
        kingstonSongs.add(new Song("Fresh"));
        kingstonSongs.add(new Song("Freestyle"));
        kingstonSongs.add(new Song("Money"));
        kingstonSongs.add(new Song("Good P"));
        kingstonSongs.add(new Song("Ghetto Youth"));
        kingstonSongs.forEach(kingston::addSong);

        List<Song> kotdSongs = new ArrayList<>();
        kotdSongs.add(new Song("Colouring This Life"));
        kotdSongs.add(new Song("Most Wanted"));
        kotdSongs.add(new Song("Open up di Door"));
        kotdSongs.add(new Song("Don't Know Someone"));
        kotdSongs.add(new Song("Lipstick"));
        kotdSongs.add(new Song("Can't Say No"));
        kotdSongs.add(new Song("Every Girl"));
        kotdSongs.add(new Song("Which Friend"));
        kotdSongs.add(new Song("Western Union"));
        kotdSongs.add(new Song("Like Google"));
        kotdSongs.add(new Song("Enemy Zone"));
        kotdSongs.add(new Song("Hey Addi"));
        kotdSongs.add(new Song("Don't Know Someone"));
        kotdSongs.add(new Song("Can't Say No"));
        kotdSongs.add(new Song("Fever"));
        kotdSongs.add(new Song("Sorry Babe"));
        kotdSongs.forEach(kotd::addSong);

        Album twoone = new Album("2001", "https://upload.wikimedia.org/wikipedia/en/5/56/DrDre-2001.jpg", "16/11/1999", "Hip-Hop", 4);
        twoone.setArtist(dre);
        dre.getAlbums().add(twoone);

        List<Song> twooneSongs = new ArrayList<>();
        twooneSongs.add(new Song("Lolo (Intro)"));
        twooneSongs.add(new Song("The Watcher"));
        twooneSongs.add(new Song("F You"));
        twooneSongs.add(new Song("Still D.R.E."));
        twooneSongs.add(new Song("Big Ego's"));
        twooneSongs.add(new Song("Xxplosive"));
        twooneSongs.add(new Song("What's the Difference"));
        twooneSongs.add(new Song("Bar One (Skit)"));
        twooneSongs.add(new Song("Light Speed"));
        twooneSongs.add(new Song("Forgot About Dre"));
        twooneSongs.add(new Song("The Next Episode"));
        twooneSongs.add(new Song("Let's Get High"));
        twooneSongs.add(new Song("B N"));
        twooneSongs.add(new Song("The Car Bomb (Skit)"));
        twooneSongs.add(new Song("Murder Ink"));
        twooneSongs.add(new Song("Ed-Ucation"));
        twooneSongs.add(new Song("Some L.A. N"));
        twooneSongs.add(new Song("Pause 4 P (Skit)"));
        twooneSongs.add(new Song("Housewife"));
        twooneSongs.add(new Song("Ackrite"));
        twooneSongs.add(new Song("Bang Bang"));
        twooneSongs.add(new Song("The Message/Outro"));
        twooneSongs.forEach(twoone::addSong);

        Album tml = new Album("Thank Me Later", "https://upload.wikimedia.org/wikipedia/en/9/9c/Drake_-_Thank_Me_Later_cover.jpg", "15/06/2010", "Hip-Hop", 5);
        Album tc = new Album("Take Care", "https://upload.wikimedia.org/wikipedia/en/a/ae/Drake_-_Take_Care_cover.jpg", "15/11/2011", "Hip-Hop", 5);
        tml.setArtist(drake);
        tc.setArtist(drake);
        drake.getAlbums().addAll(Arrays.asList(tml, tc));

        List<Song> tmlSongs = new ArrayList<>();
        tmlSongs.add(new Song("Fireworks"));
        tmlSongs.add(new Song("Karaoke"));
        tmlSongs.add(new Song("The Resistance"));
        tmlSongs.add(new Song("Over"));
        tmlSongs.add(new Song("Show Me a Good Time"));
        tmlSongs.add(new Song("Up All Night"));
        tmlSongs.add(new Song("Fancy"));
        tmlSongs.add(new Song("Shut It Down"));
        tmlSongs.add(new Song("Unforgettable"));
        tmlSongs.add(new Song("Light Up"));
        tmlSongs.add(new Song("Miss Me"));
        tmlSongs.add(new Song("Cece's Interlude"));
        tmlSongs.add(new Song("Find Your Love"));
        tmlSongs.add(new Song("Thank Me Now"));
        tmlSongs.add(new Song("Best I Ever Had"));
        tmlSongs.add(new Song("Uptown"));
        tmlSongs.add(new Song("Successful"));
        tmlSongs.forEach(tml::addSong);

        List<Song> tcSongs = new ArrayList<>();
        tcSongs.add(new Song("Over My Dead Body"));
        tcSongs.add(new Song("Shot for Me"));
        tcSongs.add(new Song("Headlines"));
        tcSongs.add(new Song("Crew Love"));
        tcSongs.add(new Song("Take Care"));
        tcSongs.add(new Song("Marvins Room"));
        tcSongs.add(new Song("Buried Alive Interlude"));
        tcSongs.add(new Song("Under Ground Kings"));
        tcSongs.add(new Song("We'll Be Fine"));
        tcSongs.add(new Song("Make Me Proud"));
        tcSongs.add(new Song("Lord Knows"));
        tcSongs.add(new Song("Cameras / Good Ones Go Interlude"));
        tcSongs.add(new Song("Doing It Wrong"));
        tcSongs.add(new Song("The Real Her"));
        tcSongs.add(new Song("Look What You've Done"));
        tcSongs.add(new Song("HYFR (Hell Ya Fucking Right)"));
        tcSongs.add(new Song("Practice"));
        tcSongs.add(new Song("The Ride"));
        tcSongs.add(new Song("The Motto"));
        tcSongs.add(new Song("Hate Sleeping Alone"));
        tcSongs.forEach(tc::addSong);

        albumRepository.saveAll(Arrays.asList(mmlp, sslp, tes, encore, recovery, mmlptwo, grodt, cb, fame, royalty,
                hoafm, breezy, eleven, iam, four, bey, renais, gggb, loud, ttt, unapologetic, anti, twoone, kingston,
                kotd, tml, tc));
    }
}
